import type { NavigationEdge } from "./types";

export const NAV_EDGES: NavigationEdge[] = [
  // 1. Classroom 204 <-> Door 204 <-> West Corridor
  {
    id: "edge-c204-dc204",
    fromNode: "node-c204",
    toNode: "node-d-c204",
    baseDistance: 4.0,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },
  {
    id: "edge-dc204-corrw",
    fromNode: "node-d-c204",
    toNode: "node-corr-w",
    baseDistance: 2.0,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },

  // 2. Workshop 203 <-> Door 203 <-> Central Junction
  {
    id: "edge-w203-dw203",
    fromNode: "node-w203",
    toNode: "node-d-w203",
    baseDistance: 4.0,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },
  {
    id: "edge-dw203-junct",
    fromNode: "node-d-w203",
    toNode: "node-junction",
    baseDistance: 2.0,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },

  // 3. Classroom 205 (Maya) <-> Door 205 <-> East Corridor
  {
    id: "edge-c205-dc205",
    fromNode: "node-c205",
    toNode: "node-d-c205",
    baseDistance: 4.0,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },
  {
    id: "edge-dc205-corre",
    fromNode: "node-d-c205",
    toNode: "node-corr-e",
    baseDistance: 2.0,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },

  // 4. Lab 201 <-> Door 201 <-> West Corridor
  {
    id: "edge-l201-dl201",
    fromNode: "node-l201",
    toNode: "node-d-l201",
    baseDistance: 4.0,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },
  {
    id: "edge-dl201-corrw",
    fromNode: "node-d-l201",
    toNode: "node-corr-w",
    baseDistance: 2.0,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },

  // 5. Lab 202 (Fire Origin) <-> Door 202 <-> Central Junction
  {
    id: "edge-l202-dl202",
    fromNode: "node-l202",
    toNode: "node-d-l202",
    baseDistance: 4.0,
    clearWidth: 1.8,
    status: "compromised",
    smokeDensity: 0.4,
    isEmergencyExit: false,
    bidirectional: true,
  },
  {
    id: "edge-dl202-junct",
    fromNode: "node-d-l202",
    toNode: "node-junction",
    baseDistance: 2.2,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.1,
    isEmergencyExit: false,
    bidirectional: true,
  },

  // 6. Chemical Store & Prep Room <-> East Corridor
  {
    id: "edge-chem-dchem",
    fromNode: "node-chem",
    toNode: "node-d-chem",
    baseDistance: 4.0,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.05,
    isEmergencyExit: false,
    bidirectional: true,
  },
  {
    id: "edge-dchem-corre",
    fromNode: "node-d-chem",
    toNode: "node-corr-e",
    baseDistance: 5.4,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },
  {
    id: "edge-prep-dprep",
    fromNode: "node-prep",
    toNode: "node-d-prep",
    baseDistance: 4.0,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },
  {
    id: "edge-dprep-corre",
    fromNode: "node-d-prep",
    toNode: "node-corr-e",
    baseDistance: 3.6,
    clearWidth: 1.8,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },

  // 7. Central Spine Corridor Connections
  {
    id: "edge-corrw-junct",
    fromNode: "node-corr-w",
    toNode: "node-junction",
    baseDistance: 15.0,
    clearWidth: 3.0,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },
  {
    id: "edge-junct-corre",
    fromNode: "node-junction",
    toNode: "node-corr-e",
    baseDistance: 15.0,
    clearWidth: 3.0,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: false,
    bidirectional: true,
  },

  // 8. West Egress Path (Exit A)
  {
    id: "edge-corrw-stairw-entry",
    fromNode: "node-corr-w",
    toNode: "node-stair-w-entry",
    baseDistance: 5.4,
    clearWidth: 2.6,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: true,
    bidirectional: true,
  },
  {
    id: "edge-stairw-entry-landing",
    fromNode: "node-stair-w-entry",
    toNode: "node-stair-w-landing",
    baseDistance: 6.0,
    clearWidth: 2.4,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: true,
    bidirectional: true,
  },
  {
    id: "edge-stairw-landing-exita",
    fromNode: "node-stair-w-landing",
    toNode: "node-exit-a",
    baseDistance: 6.0,
    clearWidth: 2.4,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: true,
    bidirectional: true,
  },
  {
    id: "edge-exita-assemblya",
    fromNode: "node-exit-a",
    toNode: "node-assembly-a",
    baseDistance: 6.0,
    clearWidth: 4.0,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: true,
    bidirectional: true,
  },

  // 9. East Egress Path (Exit B)
  {
    id: "edge-corre-staire-entry",
    fromNode: "node-corr-e",
    toNode: "node-stair-e-entry",
    baseDistance: 5.4,
    clearWidth: 2.6,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: true,
    bidirectional: true,
  },
  {
    id: "edge-staire-entry-landing",
    fromNode: "node-stair-e-entry",
    toNode: "node-stair-e-landing",
    baseDistance: 6.0,
    clearWidth: 2.4,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: true,
    bidirectional: true,
  },
  {
    id: "edge-staire-landing-exitb",
    fromNode: "node-stair-e-landing",
    toNode: "node-exit-b",
    baseDistance: 6.0,
    clearWidth: 2.4,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: true,
    bidirectional: true,
  },
  {
    id: "edge-exitb-assemblyb",
    fromNode: "node-exit-b",
    toNode: "node-assembly-b",
    baseDistance: 6.0,
    clearWidth: 4.0,
    status: "open",
    smokeDensity: 0.0,
    isEmergencyExit: true,
    bidirectional: true,
  },
];

export const edgeById = (id: string): NavigationEdge | undefined =>
  NAV_EDGES.find((edge) => edge.id === id);
